#### general settings
name: 002_EDVR_scratch_lr2e-4_600k_AI4K_LrCAR4S
use_tb_logger: true
model: video_base
distortion: sr
scale: 4
gpu_ids: [0,1,2,3,4,5,6,7]

#### datasets
datasets:
  train:
    name: AI4K
    mode: AI4K
    interval_list: [1]
    random_reverse: false
    border_mode: true
    dataroot_GT: /data1/4KHDR/crops/SDR_4K_PNG
    dataroot_LQ: /data1/4KHDR/crops/SDR_540p_PNG
    cache_keys: /home/zenghui/projects/4KHDR/keys/AI4K_keys.pkl
    train_seqs: /home/zenghui/projects/4KHDR/keys/train_seqs.pkl
    valid_seqs: /home/zenghui/projects/4KHDR/keys/valid_seqs.pkl
    scene_index: /home/zenghui/projects/4KHDR/keys/scene_idx.pkl

    N_frames: 7
    use_shuffle: true
    n_workers: 3  # per GPU
    batch_size: 16
    GT_size: 512
    LQ_size: 128
    use_flip: true
    use_rot: true
    color: RGB

  val:
    name: AI4K
    mode: AI4K
    interval_list: [1]
    random_reverse: false
    border_mode: true
    dataroot_GT: /data1/4KHDR/crops/SDR_4K_PNG
    dataroot_LQ: /data1/4KHDR/crops/SDR_540p_PNG
    cache_keys: /home/zenghui/projects/4KHDR/keys/AI4K_keys.pkl
    train_seqs: /home/zenghui/projects/4KHDR/keys/train_seqs.pkl
    valid_seqs: /home/zenghui/projects/4KHDR/keys/valid_seqs.pkl
    scene_index: /home/zenghui/projects/4KHDR/keys/scene_idx.pkl

    N_frames: 7
    use_shuffle: false
    n_workers: 3  # per GPU
    batch_size: 1
    GT_size: 512
    LQ_size: 128
    use_flip: false
    use_rot: false
    color: RGB

#### network structures
network_G:
  which_model_G: EDVR
  nf: 128
  nframes: 7
  groups: 8
  front_RBs: 5
  back_RBs: 40
  predeblur: false
  HR_in: false
  w_TSA: true

#### path
path:
  pretrain_model_G: ../experiments/pretrained_models/EDVR_L_woTSA_patch128_channel128_frame7_300k.pth
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 1e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 5e3

  manual_seed: 0

#### logger
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
